package frontendImpl;


/**
* frontendImpl/frontendAppOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontendImpl.idl
* Sunday, August 4, 2019 12:43:04 PM EDT
*/

public interface frontendAppOperations 
{

  // Manager methods
  boolean addEvent (String eventID, String eventType, int bookingCapacity, String managerID, boolean bugValue);
  boolean removeEvent (String eventID, String eventType, String managerID);
  String listEventAvailability (String eventType, String managerID);

  // Customer methods
  boolean bookEvent (String customerID, String eventID, String eventType, boolean crashValue);
  String getBookingSchedule (String customerID);
  boolean cancelEvent (String customerID, String eventID, String eventType);
  boolean swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
  void shutdown ();
} // interface frontendAppOperations
