package frontendImpl;


/**
* frontendImpl/frontendApp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontendImpl.idl
* Sunday, August 4, 2019 12:43:04 PM EDT
*/

public interface frontendApp extends frontendAppOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface frontendApp
