package frontendImpl;

/**
* frontendImpl/frontendAppHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontendImpl.idl
* Sunday, August 4, 2019 12:43:04 PM EDT
*/

public final class frontendAppHolder implements org.omg.CORBA.portable.Streamable
{
  public frontendImpl.frontendApp value = null;

  public frontendAppHolder ()
  {
  }

  public frontendAppHolder (frontendImpl.frontendApp initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = frontendImpl.frontendAppHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    frontendImpl.frontendAppHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return frontendImpl.frontendAppHelper.type ();
  }

}
