package frontendImpl;


/**
* frontendImpl/frontendAppHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontendImpl.idl
* Sunday, August 4, 2019 12:43:04 PM EDT
*/

abstract public class frontendAppHelper
{
  private static String  _id = "IDL:frontendImpl/frontendApp:1.0";

  public static void insert (org.omg.CORBA.Any a, frontendImpl.frontendApp that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static frontendImpl.frontendApp extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (frontendImpl.frontendAppHelper.id (), "frontendApp");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static frontendImpl.frontendApp read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_frontendAppStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, frontendImpl.frontendApp value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static frontendImpl.frontendApp narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof frontendImpl.frontendApp)
      return (frontendImpl.frontendApp)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      frontendImpl._frontendAppStub stub = new frontendImpl._frontendAppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static frontendImpl.frontendApp unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof frontendImpl.frontendApp)
      return (frontendImpl.frontendApp)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      frontendImpl._frontendAppStub stub = new frontendImpl._frontendAppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
