package ClientIDLInterfaceModule;


/**
* ClientIDLInterfaceModule/ClientIDLInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/workspace/log4j2/DistributedSystem_jayaprakash/DistributedSystem_jayaprakash/DistributedSystem_jayaprakash/DistributedSystem/src/main/java/Message.idl
* Monday, July 8, 2019 5:17:42 PM EDT
*/

public interface ClientIDLInterface extends ClientIDLInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientIDLInterface
