package ClientIDLInterfaceModule;

/**
* ClientIDLInterfaceModule/ClientIDLInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/workspace/log4j2/DistributedSystem_jayaprakash/DistributedSystem_jayaprakash/DistributedSystem_jayaprakash/DistributedSystem/src/main/java/Message.idl
* Monday, July 8, 2019 5:17:42 PM EDT
*/

public final class ClientIDLInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientIDLInterfaceModule.ClientIDLInterface value = null;

  public ClientIDLInterfaceHolder ()
  {
  }

  public ClientIDLInterfaceHolder (ClientIDLInterfaceModule.ClientIDLInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientIDLInterfaceModule.ClientIDLInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientIDLInterfaceModule.ClientIDLInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientIDLInterfaceModule.ClientIDLInterfaceHelper.type ();
  }

}
