package ClientIDLInterfaceModule;


/**
* ClientIDLInterfaceModule/ClientIDLInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/workspace/log4j2/DistributedSystem_jayaprakash/DistributedSystem_jayaprakash/DistributedSystem_jayaprakash/DistributedSystem/src/main/java/Message.idl
* Monday, July 8, 2019 5:17:42 PM EDT
*/

public interface ClientIDLInterfaceOperations 
{
  String AddEvent (String eventId, String eventType, int bookingCapactiy);
  String RemoveEvent (String eventId, String eventType);
  String ListEventAvailability (String eventType);
  String BookEvent (String customerId, String eventId, String eventType);
  String GetBookingSchedule (String customerId);
  boolean CancelEvent (String cutomerId, String eventId, String eventType);
  String SwapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
  void ResultHashMap ();
  void shutdown ();
} // interface ClientIDLInterfaceOperations
