package ClientIDLInterfaceModule;


/**
* ClientIDLInterfaceModule/ClientIDLInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/workspace/log4j2/DistributedSystem_jayaprakash/DistributedSystem_jayaprakash/DistributedSystem_jayaprakash/DistributedSystem/src/main/java/Message.idl
* Monday, July 8, 2019 5:17:42 PM EDT
*/

public abstract class ClientIDLInterfacePOA extends org.omg.PortableServer.Servant
 implements ClientIDLInterfaceModule.ClientIDLInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("AddEvent", new java.lang.Integer (0));
    _methods.put ("RemoveEvent", new java.lang.Integer (1));
    _methods.put ("ListEventAvailability", new java.lang.Integer (2));
    _methods.put ("BookEvent", new java.lang.Integer (3));
    _methods.put ("GetBookingSchedule", new java.lang.Integer (4));
    _methods.put ("CancelEvent", new java.lang.Integer (5));
    _methods.put ("SwapEvent", new java.lang.Integer (6));
    _methods.put ("ResultHashMap", new java.lang.Integer (7));
    _methods.put ("shutdown", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClientIDLInterfaceModule/ClientIDLInterface/AddEvent
       {
         String eventId = in.read_string ();
         String eventType = in.read_string ();
         int bookingCapactiy = in.read_long ();
         String $result = null;
         $result = this.AddEvent (eventId, eventType, bookingCapactiy);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ClientIDLInterfaceModule/ClientIDLInterface/RemoveEvent
       {
         String eventId = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.RemoveEvent (eventId, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ClientIDLInterfaceModule/ClientIDLInterface/ListEventAvailability
       {
         String eventType = in.read_string ();
         String $result = null;
         $result = this.ListEventAvailability (eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ClientIDLInterfaceModule/ClientIDLInterface/BookEvent
       {
         String customerId = in.read_string ();
         String eventId = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.BookEvent (customerId, eventId, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ClientIDLInterfaceModule/ClientIDLInterface/GetBookingSchedule
       {
         String customerId = in.read_string ();
         String $result = null;
         $result = this.GetBookingSchedule (customerId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ClientIDLInterfaceModule/ClientIDLInterface/CancelEvent
       {
         String cutomerId = in.read_string ();
         String eventId = in.read_string ();
         String eventType = in.read_string ();
         boolean $result = false;
         $result = this.CancelEvent (cutomerId, eventId, eventType);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // ClientIDLInterfaceModule/ClientIDLInterface/SwapEvent
       {
         String customerID = in.read_string ();
         String newEventID = in.read_string ();
         String newEventType = in.read_string ();
         String oldEventID = in.read_string ();
         String oldEventType = in.read_string ();
         String $result = null;
         $result = this.SwapEvent (customerID, newEventID, newEventType, oldEventID, oldEventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // ClientIDLInterfaceModule/ClientIDLInterface/ResultHashMap
       {
         this.ResultHashMap ();
         out = $rh.createReply();
         break;
       }

       case 8:  // ClientIDLInterfaceModule/ClientIDLInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClientIDLInterfaceModule/ClientIDLInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientIDLInterface _this() 
  {
    return ClientIDLInterfaceHelper.narrow(
    super._this_object());
  }

  public ClientIDLInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ClientIDLInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ClientIDLInterfacePOA
